### ISSUE TITLE
 Could you please add autopilotBlockDiagram.slx for better understanding, for which I would like to express my deep thanks.

### ISSUE THREAD

**Issue by ddd-web** [olwyk/FYP2019#2]
Could you please add autopilotBlockDiagram.slx for better understanding, for which I would like to express my deep thanks.

**Comment by olwyk** [comment]
If you would like to see a graphical representation of the autopilot I used, you can look at Appendix B of fyp_final_report.pdf. They are based on the autopilots suggested in Chapter 4 of Aircraft Control and Simulation by Brian Stevens and Frank Lewis.

**Comment by ddd-web** [comment]
Would you mind uploading the new code? I have been involved in this field for the first time, and I would like to further study through your model. I will be very grateful
------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Oliver Wykes"<notifications@github.com&gt;;
发送时间:&nbsp;2020年2月26日(星期三) 晚上6:39
收件人:&nbsp;"olwyk/FYP2019"<FYP2019@noreply.github.com&gt;;
抄送:&nbsp;"✨"<1396179127@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [olwyk/FYP2019]  Could you please add autopilotBlockDiagram.slx for better understanding, for which I would like to express my deep thanks. (#2)




Closed #2.
